title: Yes
author: Yes
url: Yes 
hostname: Yes
description: Yes
sitename: Yes
date: Yes
categories: Yes
tags: Yes
fingerprint: Yes
id: Yes
license: Yes
body: Yes
comments: Yes
commentsbody: Yes
raw_text: Yes
text: Yes
language: Yes  