title: Yes
author: No
url: Yes 
hostname: No
description: Yes
sitename: No
date: Yes
categories: No
tags: No
fingerprint: No
id: No
license: No
body: No
comments: No
commentsbody: No
raw_text: No
text: Yes
language: No  