title: Yes
author: Yes
url: Yes 
hostname: No
description: Yes
sitename: Yes
date: Yes
categories: Yes
tags: Yes
body: No
comments: Yes
commentsbody: No 
raw_text: No
text: Yes
language: No  
fingerprint: No
id: No
license: No