"service": "on"
"lifestyle": "off"
"career and education": "off"
"entertainment": "off"
"art and culture": "off"
"politics": "off"
"kids and family": "off"
"automobile": "off"
"regional": "off"
"international": "off"
"sports": "off"
"economy": "off"
"education": "off"
"multimedia": "off"
"tech": "off"
"nature": "off"
"history": "off"
"health": "off"
"opinions": "off"
"newsticker": "off"
"consumer": "off"
