"service":
  -"anzeigen"
  -"agb"
  -"abo-service"
  -"adv"
  -"app"
  -"spiele"
  -"backstage"
  -"betting"
  -"bildplus"
  -"bewerbungsaufrufe"
  -"bild-plus"
  -"brutto-netto-rechner"
  -"cartoons"
  -"corporate"
  -"corporate-site"
  -"crosswords"
  -"datenschutzerklaerung"
  -"datenschutz-spiegel"
  -"dating"
  -"dear-deidre"
  -"dienste"
  -"fuermich"
  -"games"
  -"geschaeftskonto-vergleich"
  -"gewinnspiele"
  -"gutscheine"
  -"going-out"
  -"help"
  -"humor"
  -"impressum"
  -"index"
  -"index.html"
  -"info"
  -"infografiken"
  -"inpictures"
  -"inside"
  -"insidetheguardian"
  -"jobs.badische-zeitung.de"
  -"karten"
  -"kontakt"
  -"leasing"
  -"horoskop"
  -"wissens-quiz"
  -"alltagswissen"
  -"quiz"
  -"sparfochs"
  -"mein-recht-verbraucherportal"
  -"erotik"
  -"leserforum"
  -"leserbrief"
  -"leserbriefe-68"
  -"newsletter"
  -"newsletters"
  -"produktempfehlung"
  -"produktvergleich"
  -"property"
  -"puzzles-and-games-dept"
  -"ratgeber"
  -"review"
  -"sonst"
  -"sonstiges"
  -"print"
  -"deinspiegel"
  -"spiegelgeschichte"
  -"spjc"
  -"spsm"
  -"spbest"
  -"spiegelwissen"
  -"deinspiegel"
  -"print"
  -"spiele-news"
  -"spiele-apps"
  -"spiele"
  -"sponsored"
  -"stage"
  -"tests"
  -"theguardian"
  -"ueber-uns"

"lifestyle":
  -"bauen-und-wohnen"
  -"fashion"
  -"fitness"
  -"food"
  -"genuss"
  -"heim-garten"
  -"mode"
  -"partnerschaft"
  -"trends"
  -"reise"
  -"essen-trinken"
  -"beauty"
  -"freizeit"
  -"einfach-tasty"
  -"garten"
  -"ernaehrung-diaet"
  -"lifestyle"
  -"psychologie-liebe"
  -"liebe-und-partnerschaft"
  -"lifeandstyle"
  -"shopping"
  -"stil"

"career and education":
  -"beruf-und-bildung"
  -"azubi-leben"
  -"bildung"
  -"jobs"
  -"karriere"
  -"uni"

"entertainment":
  -"boulevard"
  -"entertainment"
  -"entertainment-arts"
  -"fabulous"
  -"femail"
  -"iconist"
  -"leute"
  -"promis"
  -"sendungen"
  -"showbiz"
  -"stars"
  -"tv"
  -"tv-and-radio"
  -"tvandshowbiz"
  -"tvshowbiz"
  -"unterhaltung"

"art and culture":
  -"artanddesign"
  -"books"
  -"culture"
  -"film"
  -"kino"
  -"kinos-filme"
  -"kultur"
  -"buchtipps"
  -"serien"

"politics":
  -"politik"
  -"politics"

"kids and family":
  -"deinspiegel"
  -"familie"

"automobile":
  -"auto"
  -"technik-motor"
  -"e-mobility"
  -"mobilitaet"
  -"motors"

"regional":
  -"inland"
  -"bayern"
  -"rhein-main"
  -"deutschland"
  -"frankfurt"
  -"mecklenburg-vorpommern"
  -"hessen"
  -"sachsen"
  -"hamburg-schleswig-holstein"
  -"nordrhein-westfalen"
  -"berlin-brandenburg"
  -"lokales"
  -"burgenland"
  -"kaernten"
  -"niederoesterreich"
  -"oberoesterreich"
  -"oesterreich"
  -"salzburg"
  -"steiermark"
  -"tirol"
  -"vorarlberg"
  -"wien"
  -"california"
  -"muenchen"
  -"stadt"
  -"national"
  -"london"
  -"uk"
  -"region"
  -"regional"
  -"regionales"
  -"rtl-hessen"
  -"rtl-nord"

"international":
  -"world"
  -"ausland"
  -"ausland-1"
  -"international"
  -"international-politics"

"sports":
  -"sport"
  -"eintracht-frankfurt"
  -"fussball"
  -"football"
  -"sports"

"economy":
  -"finanzen"
  -"wirtschaft"
  -"boerse"
  -"business"
  -"capital"
  -"geld"
  -"money"
  -"unternehmen"
  -"wirtschaft-3"

"education":
  -"karriere-hochschule"

"multimedia":
  -"audio"
  -"video"
  -"podcast"
  -"bdt"
  -"episode"
  -"fotoblog"
  -"fotostrecke"
  -"media"
  -"mediathek"

"tech":
  -"smartphone-und-tablet"
  -"multimedia"
  -"computer"
  -"konsole"
  -"internet"
  -"online"
  -"technik"
  -"whatsapp"
  -"digital"
  -"netzwelt"
  -"tech"
  -"technology"

"nature":
  -"geo"
  -"klima"

"history":
  -"geschichte"

"health":
  -"gesundheit"
  -"health"
  -"medizin"
  -"medicine"

"opinions":
  -"meinung"
  -"kolumnen"
  -"kommentare"

"newsticker":
  -"newsticker"

"consumer":
  -"verbraucher"
